### ISSUE TITLE
Rear collision from background vehicle

### ISSUE THREAD

**Issue by SafeguardLi** [michigan-traffic-lab/Mcity-AV-Challenge#7]
Hello,

When we were watching the simulation from the 2nd round test, we noticed that 2 out of 10 times when the ego vehicle stopped before the stop bar, one following vehicle crashed into the ego vehicle, as shown in the screenshot.
![Screenshot from 2024-05-31 15-14-28](https://github.com/michigan-traffic-lab/Mcity-AV-Challenge/assets/41830472/0a18715d-8c14-46c0-86c3-b15297a6a2d9)

May I ask if that is a bug in the simulation platform?

Thank you. Have a good weekend.

**Comment by zhuhj-tery** [comment]
Hi,
The occurrence of rear-end collisions is not an error within the simulation platform. The behavior of background vehicles (BVs) is modeled on real human driving patterns, which may sometimes involve failing to observe the lead vehicle, resulting in a collision. These incidents, where the BV is at fault, will not significantly impact your safety rating. Therefore, we recommend that participants concentrate on avoiding crashes where the autonomous vehicle (AV) is at fault and strive to minimize collisions caused by BVs as well.
Best regards,
Mcity AV Challenge Team

**Comment by SafeguardLi** [comment]
Thank you for your reply. From our experience, this kind of accident is not very rare in the simulation platform and will kill the simulation impacting the route completion score. In that case, is it possible to tune certain parameters to reduce the probability of such incidents? Thank you.

**Comment by zhuhj-tery** [comment]
Hi,
The possibility of this kind of accident has been tuned based on the human driver statistics, so that our testing environment could accurately evaluate the safety performance of AV decision-making module in the naturalistic driving environment. Although it will impact your trajectory completion score, it is still fair for all participants. Therefore, we will not adjust certain parameters.
Best regards,
Mcity AV Challenge Team

**Comment by SafeguardLi** [comment]
Thank you for your explanation.
